apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ipl-deployment
  namespace: murali-ns
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: ipl
  template:
    metadata:
      labels:
        app: ipl
    spec:
      containers:
        - name: ipl
          image: muralisocial123/ipl:latest
          ports:
            - containerPort: 3000
          
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.container.containerPort }}
