apiVersion: v1
kind: Service
metadata:
  name: ipl-service
  namespace: murali-ns
spec:
  selector:
    app: ipl
  ports:
    - protocol: TCP
      port: 3000              # Service Port and it can be any valid port number and it is our wish
      targetPort: 3000        # Container Port on which our application is running
  type: ClusterIP          

---

# svc type NodePort
apiVersion: v1
kind: Service
metadata:
  name: ipl-service
  namespace: murali-ns
spec:
  selector:
    app: ipl
  ports:
    - protocol: TCP
      port: 3000              # Service Port and it can be any valid port number and it is our wish
      targetPort: 3000        # Container Port on which our application is running
      nodePort: 31000        # NodePort number in the range 30000-32767
  type: NodePort          # NodePort range is 30000-32767

---
# svc type LoadBalancer 

apiVersion: v1
kind: Service
metadata:
  name: ipl-service
  namespace: murali-ns
spec:
  selector:
    app: ipl
  ports:
    - protocol: TCP
      port: 3000              # Service Port and it can be any valid port number and it is our wish
      targetPort: 3000        # Container Port on which our application is running
  type: LoadBalancer

---

# svc type ExternalName

apiVersion: v1
kind: Service
metadata:
  name: ipl-service
  namespace: murali-ns
spec:
  selector:
    app: ipl
  type: ExternalName
  externalName: flipkart.com  amazon.com  jio.com  meesho.com  openai.com  chatgpt.com